server:
  port: 80
#  context-path: /web
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: pc-web

#txmanager地址
tm:
 manager:
  url: http://127.0.0.1:8899/tx/manager/
